version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: fastapi-debug-container

    ports:
      - "8000:8000"
      - "5678:5678"

    depends_on:
      - redis

    environment:
      - DEBUG_MODE=true

    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - .:/app #mounts the entire project directory to the container for live code updates. Delete in production

    command: >
      poetry run python -X frozen_modules=off
      -m debugpy
      --listen 0.0.0.0:5678
      -m uvicorn src.main:app
      --host 0.0.0.0
      --port 8000
      --reload
  
  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]  # Runs "redis-cli ping" to check if Redis is alive
      interval: 5s  # Check every 5 seconds
      timeout: 3s   # Wait max 3 seconds for a response
      retries: 5    # Try 5 times before marking as unhealthy
      start_period: 10s  # Give Redis 10 seconds to start before first health check
    volumes:
      - redis_data:/data


volumes:
  redis_data: